# Definitions {.unnumbered}

+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Approved Data Requestors                                                          | Registered businesses (government, non-government or research entities or businesses (not individuals)) who have applied under the processes stipulated in this framework and have been found to meet the requirements to be allowed a level of access to Restricted Access Species data.                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Atlas of Living Australia                                                         | National species data aggregator funded by the Australian Government's National Collaborative Research Infrastructure Strategy (NCRIS).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Biodiversity Data Repository                                                      | Database administered by the Commonwealth Department of Climate Change, Environment, Energy and Water providing highly defensible, highly curated national biodiversity data to governments, industry, and the community for decision-making, planning and reporting.                                                                                                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Darwin Core                                                                       | Darwin Core (often abbreviated to DwC) is an extension of Dublin Core for biodiversity informatics. It provides a stable standard reference for sharing information on biodiversity. The terms used in the standard are a part of a larger set of vocabularies and technical specifications under development and maintained by the Biodiversity Information Standards Group (also known by the abbreviation TDWG). TDWG is an international reference group. Its previous title was the Taxonomic Databases Working Group (hence the acronym).                                                                                                  |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data Custodians                                                                   | The managers of data repositories. For the purposes of this Framework, data custodians comprise any data custodians that have decided to operate consistent with this framework.                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data Requestor                                                                    | A user requesting data that has not yet been assessed under this framework. Data requestors that have been assessed and provided access are termed "Approved Data Requestors" (see separate definition).                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Digital Object Identifier                                                         | A unique identifier used to permanently identify a digital artefact including a link to that artefact on the internet.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Embargoed Data                                                                    | Data that has a timestamp preventing release before a certain date. It is dealt with in the [Supplement 7](supplements.html): Withheld Data and [Supplement 8](supplements.html): Process for Handling Embargoed Restricted Data.                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Existing (Legacy) Data                                                            | Existing or legacy data are data already held by a data custodian prior to the decision to act consistently with this framework.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Framework or National Framework                                                   | This document.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Full Access Users                                                                 | Users who have access to all data within the RASD (excepting Personal Identifiable Information).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Full Resolution Data                                                              | The dataset as stored by the data custodian with Personal Identifiable Information removed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jurisdictions                                                                     | Australian, State and Territory Government environmental agencies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Metadata                                                                          | For the purposes of this framework, metadata are either:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | a\) *Dataset metadata* -- a concise description of a dataset which enables a user, unable to access a dataset, to gauge the relevance of the data for their purposes; or                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | b\) *Record (or row)-level metadata* -- these are documentation at the level of a record in a dataset. For the purposes of this framework, it largely refers to documentation of the sensitivity status of the record (or the species of which it is a part) along with access constraints pertaining to the record and details of any generalisation of the data                                                                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| National Framework for the Sharing of Restricted Access Species Data in Australia | This framework. A set of guidelines for data custodians providing best practice guidance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Negotiated Legal Agreement                                                        | For the purposes of this framework, a legal agreement between data custodians and Approved Data Requestors, the terms of which are negotiated by the parties. This framework encourages the use of these agreements instead of Standard Form Data Licence Agreements.                                                                                                                                                                                                                                                                                                                                                                            |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| New Data                                                                          | Data acquired after a data custodian has decided to act consistently with this framework.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Obfuscation                                                                       | The practise of rounding or randomising, according to an agreed standard, the geo- localities in a dataset to make it difficult to discern the original geo-locality. Randomisation has benefits for map display but is not a robust data management approach in a data ecosystem. *Rounding or the provision of records as grid square polygons* is preferred if data are to be passed between systems that may then apply their own additional obfuscation. For the purposes of this framework and the best practice guide, references to obfuscation imply *rounding or the provision of records as grid square polygons*, not randomisation. |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Organisations operating and referencing this framework                            | Organisations that state publicly or reference that their processes are consistent with this framework.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Personal Identifiable Information                                                 | Data that meets the definition of private information under any of the Commonwealth, State or Territory legislative or regulatory definitions. For the purposes of Restricted Access Species Data, generally names and/or contact details held in third-party datasets where the record contributor has not given permission for the sharing of their data. Discussed in full in [Supplement 3](supplements.html).                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Raw Data                                                                          | Restricted Access Species (RASD) as stored by the data custodian including Personal Identifiable Information.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Registered Business                                                               | A legal entity with a registered Australian Business Number. May be a government, non-government, or research organisation, or a business.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Restricted Access Species Data (RASD)                                             | For the purposes of this framework, RASD are any dataset or record related to species that is determined to contain restricted access or sensitive information (data class or geolocational) as defined by this framework that should not be shared openly. RASD categories are defined in [Table 1](principle-consistently-classified.html#table-1---risk-matrix-for-rasd).                                                                                                                                                                                                                                                                     |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Restricted Access Species List (RASL)                                             | RASLs, also known as sensitive species lists, are maintained by each jurisdiction in Australia. A jurisdictional RASL is a publicly available list that delineates which species should have their geographic locations blurred or obfuscated to prevent disturbance or exploitation of the species or the site. In addition, Third-party data custodians (including individuals) may have their own RASLs.                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Species                                                                           | In the context of this framework, species refer to all species, subspecies or infraspecies, including (where identified under RASLs) populations, varieties, and phrase name taxa.                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Standard Form Data Licence Agreement                                              | A license used between most data custodians and repositories, which uses standard (non-negotiable) terms and conditions to stipulate management of data including to control end user use of data.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Transformation                                                                    | The practice of modifying the fields or data in a dataset. For the purpose of this framework:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | Transformation involves:\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                   | (i) the bulk manipulation of data to desensitise for exchange or sharing, including obfuscation;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | Removals include one or more of the following:\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | (i) removing Personal Identifiable Information\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | (ii) removing fields containing sensitive data (other than Personal Identifiable Information)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                   | (iii) removing rows containing sensitive data (other than Personal Identifiable Information)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                   | (iv) temporarily removing data held under an embargo\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                   | (v) removing data with legal or identification constraints                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | Flagging includes one or more of the following:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                   | (i) adjustment of "local" taxonomy to an agreed national standard (while retaining local taxonomy as well)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                   | (ii) flagging of suspect records.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Withheld Data                                                                     | Data which does not leave a Data Custodian's database at all UNLESS relevant transformations metadata and removals outlined in this framework are applied. May be a full dataset or fields within a dataset. Withheld data are dealt with in [Supplement 7](supplements.html).                                                                                                                                                                                                                                                                                                                                                                   |
+-----------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
