# Supplement 4: Restricted Access Species Data Metadata Statement Template {.unnumbered}

*(Version 1/12/2022)*

It is best practice for all data, even withheld data, to have a publicly available metadata statement. This is an important principle of the RASD Framework. Data custodians should share metadata for all datasets including those datasets that cannot be shared (i.e. withheld) with any other user, including other jurisdictions.

The metadata statement fields are shown in the Table below. It is recommended that asterisked fields be treated as mandatory and required for all datasets including withheld datasets.

## Table: Metadata Fields for RASD

+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Metadata Field            | Description                                                                                                                                                                               | Example content                                                                                                                                                                                                                          |
+===========================+===========================================================================================================================================================================================+==========================================================================================================================================================================================================================================+
| \*Title                   | The name of the dataset                                                                                                                                                                   | NT Herbaria Flora Specimen Records                                                                                                                                                                                                       |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Abstract                  | A brief description of what the data contains including the purpose for which it was collected if relevant                                                                                | Database of all flora records that are managed by the Department of Natural Resources and the Environment. Records are derived from the NT Vegetation Site Database and HOLTZE (N.T. Herbarium specimen) database and NT Weeds database. |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Key Word (s)            | Key words to enhance discoverability and searchability of the dataset                                                                                                                     | Flora, Fauna, species, sensitive, NSW                                                                                                                                                                                                    |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Date Range              | Start and end dates of data collection -- may be able to be generated from the data                                                                                                       | 01/12/2010-present\                                                                                                                                                                                                                      |
|                           |                                                                                                                                                                                           | 31/07/1788-21/10/1983                                                                                                                                                                                                                    |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Geographic Extent       | Bounding box generated from the data                                                                                                                                                      | Bounding Coordinates: North Bounding Coordinate: -10\                                                                                                                                                                                    |
|                           |                                                                                                                                                                                           | South Bounding Coordinate: -26\                                                                                                                                                                                                          |
|                           |                                                                                                                                                                                           | East Bounding Coordinate: 138\                                                                                                                                                                                                           |
|                           |                                                                                                                                                                                           | West Bounding Coordinate: 129                                                                                                                                                                                                            |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Taxa covered            | List of unique species covered by the dataset or if contains all taxa under a higher level classification then the taxonomic group(s) covered (may be able to be generated from the data) | All Flora\                                                                                                                                                                                                                               |
|                           |                                                                                                                                                                                           | Mammalia\                                                                                                                                                                                                                                |
|                           |                                                                                                                                                                                           | Orchidaceae\                                                                                                                                                                                                                             |
|                           |                                                                                                                                                                                           | *Wollemia nobilis*                                                                                                                                                                                                                       |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Collection methods      | Method of data collection (drop down list) -- includes unknown / other where the method of collection is not known)                                                                       | Incidental observations\                                                                                                                                                                                                                 |
|                           |                                                                                                                                                                                           | Systematic survey                                                                                                                                                                                                                        |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Data Source             | URI / DOI for the dataset                                                                                                                                                                 | doi:10.4227/05/508637F997933                                                                                                                                                                                                             |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Embargoed?              | Yes / No field                                                                                                                                                                            | Yes                                                                                                                                                                                                                                      |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Embargo Release Date      | If embargoed, the date that the data may be released                                                                                                                                      | 30/06/2022                                                                                                                                                                                                                               |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Custodian               | Organisation / body who is the data custodian (may be different from contact organisation)                                                                                                | NT, Department of Environment, Parks and Water Security                                                                                                                                                                                  |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Contact Organisation    | Organisation who is the point of contact for the dataset                                                                                                                                  | Department of Agriculture Water and the Environment                                                                                                                                                                                      |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Contact Position        | Position for the point of contact for the dataset                                                                                                                                         | Data Manager                                                                                                                                                                                                                             |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Contact Email           | Email address for the point of contact for the dataset                                                                                                                                    | data\@awe.gov.au                                                                                                                                                                                                                         |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Stored Format           | Primary format of the dataset                                                                                                                                                             | ArcGIS shapefile                                                                                                                                                                                                                         |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Available Formats         | Other formats which the data can be made available                                                                                                                                        | csv, Blob                                                                                                                                                                                                                                |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Access Rights           | Any access restrictions based on privacy, security or other policies that apply to how this data are accessed                                                                             | Controlled vocabulary e.g.\                                                                                                                                                                                                              |
|                           |                                                                                                                                                                                           | 11 - Open\                                                                                                                                                                                                                               |
|                           |                                                                                                                                                                                           | 12 - Open with Exemptions\                                                                                                                                                                                                               |
|                           |                                                                                                                                                                                           | 13 - Closed\                                                                                                                                                                                                                             |
|                           |                                                                                                                                                                                           | 14 - May be Released Under FOI\                                                                                                                                                                                                          |
|                           |                                                                                                                                                                                           | 15 - Not for Release\                                                                                                                                                                                                                    |
|                           |                                                                                                                                                                                           | 16 - May be Published\                                                                                                                                                                                                                   |
|                           |                                                                                                                                                                                           | 17 - Limited Release\                                                                                                                                                                                                                    |
|                           |                                                                                                                                                                                           | 98 -- Unspecified\                                                                                                                                                                                                                       |
|                           |                                                                                                                                                                                           | 99 -- Not Applicable                                                                                                                                                                                                                     |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Use Restrictions        | Any specific use constraints on the dataset including legal, restricted access species, embargo periods etc in addition to access rights                                                  | Internal use only, not to be passed onto third parties without consent                                                                                                                                                                   |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Security Classification | The security classification applied to the dataset as specified under the Australian Government Protective Security Policy Framework or jurisdictional equivalent                         | Official, Official: sensitive                                                                                                                                                                                                            |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \*Generalisations †       | Any rulesets which have been applied at a dataset level to obfuscate or generalise either species attributes or location                                                                  | Locations obfuscated to 2 decimal places and attribute Habitat removed from dataset.                                                                                                                                                     |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

\* Mandatory Fields\
† In addition to the dataset level metadata, row level metadata regarding generalisations applied to individual rows in a dataset is required for transparency and custodians should look at the suggested treatments and metadata in [Supplement 5](supplement5.qmd).
